// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kuysucqllyqfgbnphnks.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt1eXN1Y3FsbHlxZmdibnBobmtzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMyMDczMDEsImV4cCI6MjA4ODc4MzMwMX0.hyetC5kmB1dGpicN7pPHAxx6iDV02UNSDumOX8IWnEM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});